# Assay GitHub Action
# Usage:
#   - uses: assay-dev/assay-action@v1
#     with:
#       policy: policies/agent.yaml
#       traces: traces/
#       min-coverage: 80

name: 'Assay Policy Check'
description: 'Deterministic policy enforcement for AI agent tool calls'
author: 'Assay'

branding:
  icon: 'shield'
  color: 'blue'

inputs:
  policy:
    description: 'Path to policy YAML file'
    required: true
  traces:
    description: 'Path to traces file (JSONL) or directory'
    required: true
  min-coverage:
    description: 'Minimum coverage threshold (0-100)'
    required: false
    default: '80'
  fail-on-high-risk:
    description: 'Fail if high-risk tools are uncovered'
    required: false
    default: 'true'
  version:
    description: 'Assay version to use'
    required: false
    default: 'latest'
  format:
    description: 'Output format: summary, json, markdown, github'
    required: false
    default: 'github'

outputs:
  coverage:
    description: 'Overall coverage percentage'
    value: ${{ steps.assay.outputs.coverage }}
  meets-threshold:
    description: 'Whether coverage meets threshold'
    value: ${{ steps.assay.outputs.meets_threshold }}
  report:
    description: 'Path to coverage report'
    value: ${{ steps.assay.outputs.report }}

runs:
  using: 'composite'
  steps:
    - name: Determine OS and Architecture
      id: platform
      shell: bash
      run: |
        OS=$(uname -s | tr '[:upper:]' '[:lower:]')
        ARCH=$(uname -m)
        case "$ARCH" in
          x86_64) ARCH="x86_64" ;;
          aarch64|arm64) ARCH="aarch64" ;;
          *) echo "Unsupported architecture: $ARCH"; exit 1 ;;
        esac
        case "$OS" in
          linux) TARGET="${ARCH}-unknown-linux-gnu" ;;
          darwin) TARGET="${ARCH}-apple-darwin" ;;
          *) echo "Unsupported OS: $OS"; exit 1 ;;
        esac
        echo "target=$TARGET" >> $GITHUB_OUTPUT
        echo "Platform: $TARGET"

    - name: Cache Assay Binary
      id: cache
      uses: actions/cache@v4
      with:
        path: ~/.assay/bin
        key: assay-${{ inputs.version }}-${{ steps.platform.outputs.target }}

    - name: Install Assay
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir -p ~/.assay/bin
        VERSION="${{ inputs.version }}"
        TARGET="${{ steps.platform.outputs.target }}"
        
        if [ "$VERSION" = "latest" ]; then
          # Get latest release tag
          VERSION=$(curl -sL https://api.github.com/repos/assay-dev/assay/releases/latest | grep '"tag_name"' | cut -d'"' -f4)
        fi
        
        DOWNLOAD_URL="https://github.com/assay-dev/assay/releases/download/${VERSION}/assay-${VERSION}-${TARGET}.tar.gz"
        echo "Downloading Assay ${VERSION} for ${TARGET}..."
        curl -sL "$DOWNLOAD_URL" | tar xz -C ~/.assay/bin
        chmod +x ~/.assay/bin/assay
        ~/.assay/bin/assay --version

    - name: Add Assay to PATH
      shell: bash
      run: echo "$HOME/.assay/bin" >> $GITHUB_PATH

    - name: Run Assay Coverage
      id: assay
      shell: bash
      run: |
        # Create report directory
        mkdir -p .assay-reports
        REPORT_FILE=".assay-reports/coverage-report.json"
        
        # Build command
        CMD="assay coverage"
        CMD="$CMD --policy '${{ inputs.policy }}'"
        CMD="$CMD --traces '${{ inputs.traces }}'"
        CMD="$CMD --min-coverage ${{ inputs.min-coverage }}"
        CMD="$CMD --format ${{ inputs.format }}"
        CMD="$CMD --output $REPORT_FILE"
        
        if [ "${{ inputs.fail-on-high-risk }}" = "true" ]; then
          CMD="$CMD --fail-on-high-risk"
        fi
        
        echo "Running: $CMD"
        
        # Run and capture exit code
        set +e
        eval $CMD
        EXIT_CODE=$?
        set -e
        
        # Parse results for outputs
        if [ -f "$REPORT_FILE" ]; then
          COVERAGE=$(jq -r '.overall_coverage_pct // 0' "$REPORT_FILE")
          MEETS=$(jq -r '.meets_threshold // false' "$REPORT_FILE")
          echo "coverage=$COVERAGE" >> $GITHUB_OUTPUT
          echo "meets_threshold=$MEETS" >> $GITHUB_OUTPUT
          echo "report=$REPORT_FILE" >> $GITHUB_OUTPUT
        fi
        
        # Exit with original code
        exit $EXIT_CODE

    - name: Upload Coverage Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: assay-coverage-report
        path: .assay-reports/
        retention-days: 30
