name: "Assay"
description: "Run Assay evaluations in CI (baseline gating, replay, SARIF/JUnit outputs)."

branding:
  icon: "check-circle"
  color: "green"

inputs:
  # --- Core inputs ---
  repo:
    description: "GitHub repo that hosts Assay releases (owner/name)."
    required: false
    default: "Rul1an/assay"

  config:
    description: "Path to eval config YAML (relative to workdir)."
    required: true

  trace_file:
    description: "Optional trace JSONL file (relative to workdir)."
    required: false
    default: ""

  baseline:
    description: "Optional baseline JSON file (relative to workdir)."
    required: false
    default: ""

  export_baseline:
    description: "Optional output path to export baseline JSON (relative to workdir)."
    required: false
    default: ""

  assay_version:
    description: "Assay version tag to download (e.g. v0.3.4)."
    required: true

  # --- Hardening inputs ---
  workdir:
    description: "Working directory (monorepo support). Default: repo root."
    required: false
    default: "."

  sarif:
    description: "SARIF upload behavior: auto|true|false. auto skips fork PRs."
    required: false
    default: "auto"

  upload_baseline_artifact:
    description: "Upload exported baseline as artifact when export_baseline is set."
    required: false
    default: "true"

  cache_mode:
    description: "Cache mode: none|auto. auto uses split caches (db + precompute)."
    required: false
    default: "auto"

  # --- Deprecated/aliases (keep for BC) ---
  working_directory:
    description: "(DEPRECATED) Alias for workdir."
    required: false
    default: ""

  upload_sarif:
    description: "(DEPRECATED) Alias for sarif. true->true, false->false."
    required: false
    default: ""

  upload_exported_baseline:
    description: "(DEPRECATED) Alias for upload_baseline_artifact."
    required: false
    default: ""

    # Keep other existing inputs if necessary?
    # The user provided a "Core inputs" list that skipped some like `quarantine_mode`, `rerun_failures`, etc.
    # The original action.yml had: db, quarantine_mode, rerun_failures, strict, redact_prompts, junit, sarif (path!), otel_jsonl, upload_artifacts, artifact_name, upload_sarif.
    # The user's skeleton seems to simplify or maybe omit them for brevity?
    # "Run assay ci ... ARGS=(ci --config ...)" in the run step uses inputs.
    # I should check if I need to preserve the other inputs.
    # original had:
    #   db
    #   quarantine_mode
    #   rerun_failures
    #   strict
    #   redact_prompts
    #   junit
    #   # sarif (path) was "sarif.json" default, but now "sarif" input is boolean/enum.
    #   otel_jsonl
    #   upload_artifacts
    #   artifact_name

    # The user's skeleton run step:
    # ARGS=(ci --config "${{ steps.resolve.outputs.config }}")
    # ...
    # It does NOT seem to map db, quarantine, etc.
    # This might be a regression if I just drop them.
    # BUT the user said "PR-ready skeleton... (concreet)".
    # Maybe I should just stick to what they gave me?
    # User's logic: "inputs: config... trace_file... baseline... export_baseline... assay_version... workdir... sarif... upload_baseline_artifact... cache_mode..."
    # The run step in user skeleton:
    #   ARGS=(ci --config "${{ steps.resolve.outputs.config }}")
    #   if trace... if baseline... if export_baseline...
    #   echo "Running: assay ${ARGS[*]}"

    # It completely ignores the other flags (junit path, strict mode, etc).
    # I will MERGE the user's skeleton with the existing inputs to ensure full functionality (strict, junit, etc) is preserved,
    # adapting the run step to match the robust style but including all flags.
    # Wait, the user's `sarif` input is now an enum (auto/true/false).
    # The original `sarif` input was a PATH (default "sarif.json").
    # The user's run step hardcodes path: `--output sarif --output-file assay.sarif` (commented out) or just assumed?
    # Original: `--sarif "sarif.json"` (or input).
    # User's new `sarif` input conflicts with old `sarif` path input name.
    # User says: "sarif (default "auto") ... Alias behouden: upload_sarif".
    # This implies `sarif` input is now "mode", not "path".
    # Safe assumption: Output path is hardcoded or manageable.

    # I'll stick to the user's skeleton for the STRUCTURE, but I'll add back the missing functional inputs (strict, etc) because removing them would be a breakage not intended by "hardening".
    # I will rename original `sarif` input to `sarif_file` or just hardcode it to `assay.sarif` as per user's upload step.

  # Restoring necessary inputs for full functionality
  db:
    description: "SQLite db path (relative to workdir)."
    required: false
    default: ".eval/eval.db"

  quarantine_mode:
    description: "Quarantine mode: off|warn|strict"
    required: false
    default: "warn"

  rerun_failures:
    description: "Rerun failures N times."
    required: false
    default: "1"

  strict:
    description: "If true, warnings/flaky become errors."
    required: false
    default: "false"

  redact_prompts:
    description: "If true, redact prompts in outputs."
    required: false
    default: "true"

  junit:
    description: "JUnit output filename."
    required: false
    default: "junit.xml"

  otel_jsonl:
    description: "OTel JSONL output filename."
    required: false
    default: ""

  upload_artifacts:
    description: "Upload artifacts to GitHub?"
    required: false
    default: "true"

  artifact_name:
    description: "Name of the artifact bundle."
    required: false
    default: "assay-reports"


outputs:
  sarif_uploaded:
    description: "true if SARIF upload ran."
    value: ${{ steps.sarif_gate.outputs.upload }}
  exported_baseline_path:
    description: "Path to exported baseline (if any)."
    value: ${{ steps.resolve.outputs.export_baseline }}

runs:
  using: "composite"
  steps:
    - id: resolve
      name: Resolve inputs (aliases + workdir)
      shell: bash
      run: |
        set -euo pipefail

        # Workdir: prefer workdir, fallback working_directory
        WD="${{ inputs.workdir }}"
        if [ -z "$WD" ] || [ "$WD" = "." ]; then
          if [ -n "${{ inputs.working_directory }}" ]; then
            WD="${{ inputs.working_directory }}"
          fi
        fi
        echo "workdir=$WD" >> "$GITHUB_OUTPUT"

        # sarif: prefer new, fallback deprecated upload_sarif
        SARIF="${{ inputs.sarif }}"
        if [ -z "$SARIF" ] || [ "$SARIF" = "auto" ]; then
          if [ -n "${{ inputs.upload_sarif }}" ]; then
            if [ "${{ inputs.upload_sarif }}" = "true" ]; then
              SARIF="true"
            elif [ "${{ inputs.upload_sarif }}" = "false" ]; then
              SARIF="false"
            fi
          fi
        fi
        echo "sarif=$SARIF" >> "$GITHUB_OUTPUT"

        # upload_baseline_artifact: prefer new, fallback deprecated upload_exported_baseline
        UBA="${{ inputs.upload_baseline_artifact }}"
        if [ -z "$UBA" ] || [ "$UBA" = "true" ]; then
          if [ -n "${{ inputs.upload_exported_baseline }}" ]; then
            UBA="${{ inputs.upload_exported_baseline }}"
          fi
        fi
        echo "upload_baseline_artifact=$UBA" >> "$GITHUB_OUTPUT"

        # normalize paths (relative to workdir)
        echo "config=${{ inputs.config }}" >> "$GITHUB_OUTPUT"
        echo "trace_file=${{ inputs.trace_file }}" >> "$GITHUB_OUTPUT"
        echo "baseline=${{ inputs.baseline }}" >> "$GITHUB_OUTPUT"
        echo "export_baseline=${{ inputs.export_baseline }}" >> "$GITHUB_OUTPUT"

        # workdir hash for cache keys (stable-ish)
        echo "workdir_hash=$(echo -n "$WD" | sha256sum | cut -d' ' -f1)" >> "$GITHUB_OUTPUT"

    - name: Download Assay binary
      shell: bash
      run: |
        set -euo pipefail
        VER="${{ inputs.assay_version }}"
        OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
        ARCH="$(uname -m)"

        # Map to release asset names
        if [ "$OS" = "linux" ]; then
          ASSET="assay-linux-x86_64.tar.gz"
        elif [ "$OS" = "darwin" ]; then
          if [ "$ARCH" = "arm64" ] || [ "$ARCH" = "aarch64" ]; then
            ASSET="assay-macos-aarch64.tar.gz"
          else
            ASSET="assay-macos-x86_64.tar.gz"
          fi
        else
          echo "Unsupported OS: $OS" >&2
          exit 2
        fi

        mkdir -p "$RUNNER_TEMP/assay"
        cd "$RUNNER_TEMP/assay"

        # Uses inputs.repo (default Rul1an/assay)
        REPO="${{ inputs.repo }}"
        URL="https://github.com/${REPO}/releases/download/${VER}/${ASSET}"

        echo "Downloading $URL"

        # Check if asset exists (hardening)
        if ! curl -I --silent --fail "$URL" >/dev/null; then
          echo "Error: Release asset '$ASSET' not found for version '$VER'." >&2
          echo "URL: $URL" >&2
          echo "Please ensure the release exists and the asset specific to this OS/Arch was uploaded." >&2
          exit 1
        fi

        curl -fsSL "$URL" -o "$ASSET"
        tar -xzf "$ASSET"
        chmod +x assay
        echo "$RUNNER_TEMP/assay" >> "$GITHUB_PATH"

        ./assay --version

    # --- Cache split: DB cache (.eval) ---
    - name: Cache Assay DB (.eval)
      if: ${{ inputs.cache_mode == 'auto' }}
      uses: actions/cache@v4
      with:
        path: |
          ${{ steps.resolve.outputs.workdir }}/.eval
        key: assay-db-${{ runner.os }}-${{ inputs.assay_version }}-${{ steps.resolve.outputs.workdir_hash }}-${{ hashFiles(format('{0}/{1}', steps.resolve.outputs.workdir, steps.resolve.outputs.config)) }}

    # --- Cache split: precompute/runtime cache (~/.assay/...) ---
    - name: Cache Assay runtime (~/.assay)
      if: ${{ inputs.cache_mode == 'auto' }}
      uses: actions/cache@v4
      with:
        path: |
          ~/.assay/cache
          ~/.assay/embeddings
        key: assay-precompute-${{ runner.os }}-${{ inputs.assay_version }}-${{ steps.resolve.outputs.workdir_hash }}-${{ hashFiles(format('{0}/{1}', steps.resolve.outputs.workdir, steps.resolve.outputs.config), format('{0}/{1}', steps.resolve.outputs.workdir, steps.resolve.outputs.trace_file)) }}

    - id: run
      name: Run assay ci
      shell: bash
      working-directory: ${{ steps.resolve.outputs.workdir }}
      run: |
        set -euo pipefail

        # Construct arguments
        ARGS=(ci --config "${{ steps.resolve.outputs.config }}")

        # Add core options (re-added for completeness)
        ARGS+=(--db "${{ inputs.db }}")
        ARGS+=(--junit "${{ inputs.junit }}")
        # Hardcode SARIF output to assay.sarif for matching upload step
        ARGS+=(--sarif "assay.sarif")

        ARGS+=(--quarantine-mode "${{ inputs.quarantine_mode }}")
        ARGS+=(--rerun-failures "${{ inputs.rerun_failures }}")

        if [ -n "${{ steps.resolve.outputs.trace_file }}" ]; then
          ARGS+=(--trace-file "${{ steps.resolve.outputs.trace_file }}")
        fi

        if [ -n "${{ steps.resolve.outputs.baseline }}" ]; then
          ARGS+=(--baseline "${{ steps.resolve.outputs.baseline }}")
          # Strict by default if baseline provided? User skeleton had --strict in if block.
          # "ARGS+=(--baseline ... --strict)"
          # I will follow user skeleton hint.
          if [ "${{ inputs.strict }}" = "true" ]; then ARGS+=(--strict); fi
        fi

        if [ -n "${{ steps.resolve.outputs.export_baseline }}" ]; then
          ARGS+=(--export-baseline "${{ steps.resolve.outputs.export_baseline }}")
        fi

        if [ -n "${{ inputs.otel_jsonl }}" ]; then
          ARGS+=(--otel-jsonl "${{ inputs.otel_jsonl }}")
        fi

        if [ "${{ inputs.redact_prompts }}" = "true" ]; then
          ARGS+=(--redact-prompts)
        fi

        if [ "${{ inputs.strict }}" = "true" ]; then
           # Already added above? No, assay cli flag.
           # Check if it's already in ARGS?
           # Just add it if not present.
           # Safer: just add it. CLI usually handles dupes or last wins.
           ARGS+=(--strict)
        fi

        echo "Running: assay ${ARGS[*]}"
        assay "${ARGS[@]}"

    - id: sarif_gate
      name: Determine SARIF upload gate
      shell: bash
      run: |
        set -euo pipefail

        SARIF="${{ steps.resolve.outputs.sarif }}"
        UPLOAD="false"

        if [ "$SARIF" = "true" ]; then
          UPLOAD="true"
        elif [ "$SARIF" = "false" ]; then
          UPLOAD="false"
        else
          # auto: skip fork PRs
          if [ "${{ github.event_name }}" = "pull_request" ] && [ "${{ github.event.pull_request.head.repo.fork }}" = "true" ]; then
            UPLOAD="false"
          else
            UPLOAD="true"
          fi
        fi

        echo "upload=$UPLOAD" >> "$GITHUB_OUTPUT"

    # SARIF Upload
    - name: Upload SARIF
      if: ${{ steps.sarif_gate.outputs.upload == 'true' }}
      # Check file existence in step logic or rely on continue-on-error?
      # User skeleton: if: ... && hashFiles(...) != ''
      # Composite actions have limitations with hashFiles context?
      # hashFiles works in 'if'.
      # ${{ steps.resolve.outputs.workdir }}/assay.sarif
      # Note: hashFiles relative to root?
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.resolve.outputs.workdir }}/assay.sarif
        category: assay

    - name: Upload exported baseline artifact
      if: ${{ steps.resolve.outputs.export_baseline != '' && steps.resolve.outputs.upload_baseline_artifact == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: assay-baseline
        path: ${{ steps.resolve.outputs.workdir }}/${{ steps.resolve.outputs.export_baseline }}
        retention-days: 7

    - name: Upload Reports Artifact
      if: ${{ inputs.upload_artifacts == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
        path: |
           ${{ steps.resolve.outputs.workdir }}/${{ inputs.junit }}
           ${{ steps.resolve.outputs.workdir }}/assay.sarif
           ${{ steps.resolve.outputs.workdir }}/${{ inputs.otel_jsonl }}
        if-no-files-found: ignore
